name: Build and push

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    name: Build and publish image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker metadata
        id: docker_metadata
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/significa/simple-ios-ipa-app-distribution
          tags: |
            type=sha
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Get app version
        id: get_app_version
        shell: bash
        run: |
          if [[ "$IS_PRODUCTION" == "true" ]]; then
           echo "version=$(echo ${{ github.ref_name }} | sed -e 's/^v//')" >> "$GITHUB_OUTPUT"
          else
            echo "version=$(echo 0.0.1-${{ github.sha }})" >> "$GITHUB_OUTPUT"
           fi
        env:
          IS_PRODUCTION: ${{ (github.event_name == 'release' || github.event_name == 'workflow_dispatch') && github.ref_type == 'tag' && startsWith(github.ref_name, 'v')}}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64/v8
          push: true
          tags: ${{ steps.docker_metadata.outputs.tags }}
          labels: ${{ steps.docker_metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            APP_VERSION=${{ steps.get_app_version.outputs.version }}
